### ISSUE TITLE
[Documentation] Update Slack link to be the actual invite link instead of main team page

### ISSUE THREAD

**Issue by theromit** [paypal/gimel#123]
**What feature are your requesting?**
The Slack link in the readme points to gimel-dev.slack.com but that does not give an easy way to join the team. There is an invite link within Slack which will be better. 

**What benefits do you foresee from the feature you are requesting?**
Anyone should be able to easily join the Slack team

**Potential solution/ideas?**
Change the URL to the invite link

**Additional context**

**Comment by Dee-Pac** [comment]
Closed with #124

**Comment by Dee-Pac** [comment]
closing manually since above comment did not auto-close the issue.
