### ISSUE TITLE
[UDC] Unified Data Catalog Web UI

### ISSUE THREAD

**Issue by rampallydheeraj** [paypal/gimel#125]
**What feature are your requesting?**
This feature would encompass building a Web-UI which would be helpful for exploring datasets

**What benefits do you foresee from the feature you are requesting?**
The ease in which you would explore datasets across enterprise would be drastically reduced.

**Potential solution/ideas?**
Gimel can integrate with UDC to retrieve metadata of a specific dataset

**Comment by Dee-Pac** [comment]
Merged.
