### ISSUE TITLE
[Connector] [JDBC] Feature to read password from user rather than from HDFS file

### ISSUE THREAD

**Issue by rajarshisarkar** [paypal/gimel#156]
**What feature are your requesting?**

Read password from user rather than from HDFS file

**What benefits do you foresee from the feature you are requesting?**

Currently, users can put JDBC source password in an HDFS file and the Gimel connector reads the password from there. This causes a tight coupling with HDFS.

**Potential solution/ideas?**

Read password directly from user

**Additional context**

Refer `gimel.jdbc.p.file` here: https://github.com/paypal/gimel/blob/master/docs/gimel-connectors/teradata.md#teradata-read-options

**Comment by rajarshisarkar** [comment]
Made code changes to 

```
modified:   gimel-dataapi/gimel-connectors/gimel-jdbc/src/main/scala/com/paypal/gimel/jdbc/conf/JdbcConfigs.scala
        modified:   gimel-dataapi/gimel-connectors/gimel-jdbc/src/main/scala/com/paypal/gimel/jdbc/utilities/JDBCAuthUtilities.scala
        modified:   gimel-dataapi/gimel-connectors/gimel-jdbc/src/main/scala/com/paypal/gimel/jdbc/utilities/JDBCCommons.scala
```

Unable to push the code:
```
$ git push -u origin readPasswordFromUser
remote: Permission to paypal/gimel.git denied to rajarshisarkar.
fatal: unable to access 'https://github.com/paypal/gimel/': The requested URL returned error: 403
```

**Comment by rajarshisarkar** [comment]
@Dee-Pac @bthilakraj Can you please provide the access to push the code.

**Comment by laxpatil** [comment]
@rajarshisarkar : Please check https://gimel.readthedocs.io/en/master/CONTRIBUTING/. you need to fork and raise pull request from your fork. 

Thanks,
Laxmikant

**Comment by laxpatil** [comment]
Looks good to me. Thanks!
