### ISSUE TITLE
Need latest docker image for Gimel 

### ISSUE THREAD

**Issue by saivenkatg5** [paypal/gimel#169]
Hi Team,
We have been exploring gimel for the last 6 months and the security team has recently identified the vulnerability with older kibana version 5.6.15 and this issue can be fixed , if we upgrade it to latest version of kibana 6.6.1. Hence provide the latest docker image of gimel.

**Comment by Dee-Pac** [comment]
Hi @saivenkatg5 Close this request as No Fix Required as per our conversation on emails.
Please do reopen the issue, if there is a need.
