### ISSUE TITLE
[Docs] Add a code of conduct doc

### ISSUE THREAD

**Issue by theromit** [paypal/gimel#34]
Need to add a code of conduct doc for community guidelines.

**Comment by Dee-Pac** [comment]
Could you please come up with the writeup draft? @theromit 
Once we finalize a code - you can give a PR.

**Comment by Dee-Pac** [comment]
https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

**Comment by theromit** [comment]
An example: https://www.apache.org/foundation/policies/conduct

**Comment by r39132** [comment]
I +1 the notion of adopting the Apache code of conduct!
