### ISSUE TITLE
[Connector] [Dropzone] Create Gimel SFTP or Dropzone Connector

### ISSUE THREAD

**Issue by prabhu1984** [paypal/gimel#42]
Spark open source world has SFTP connector. We can add a similar connector on Gimel to support SFTP or Dropzone in/out data consumption.

https://github.com/springml/spark-sftp/blob/master/README.md

Thanks
Prabhu

**Comment by Dee-Pac** [comment]
Exploring this ...

**Comment by Dee-Pac** [comment]
This is addressed via #122
