### ISSUE TITLE
[Connector] [Kafka] Improve code coverage in Kafka Modules

### ISSUE THREAD

**Issue by Dee-Pac** [paypal/gimel#6]
Add Test Cases in the most sensitive segments of the Kafka Module.

**Comment by djKooks** [comment]
Hello,
Is test running on kafka module? I couldn't find in log. Or maybe I'm doing something wrong...

**Comment by Dee-Pac** [comment]
@djKooks I realized the scalatest module is missing in the pom.xml of project `gimel-dataapi/gimel-connectors/gimel-kafka-0.1.0`

By adding the snippet below, the tests would execute. 

```xml
      <plugin>
        <groupId>org.scalatest</groupId>
        <artifactId>scalatest-maven-plugin</artifactId>
        <version>1.0</version>
        <configuration>
          <reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
          <junitxml>.</junitxml>
          <filereports>WDF TestSuite.txt</filereports>
        </configuration>
        <executions>
          <execution>
            <id>test</id>
            <goals>
              <goal>test</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

Please let me know if you'd be ok to add the snippet and work on your fixes.

**Comment by djKooks** [comment]
@Dee-Pac yes, it works now. Thanks!
Is there a reason not putting this setting for kafka module?

**Comment by Dee-Pac** [comment]
@djKooks Yes, you are right. DataSetUtilsSpec is not.
Also, there is an issue open to add the missing scalatest plugin.

https://github.com/paypal/gimel/issues/63

Are you planing to add tests??

**Comment by djKooks** [comment]
@Dee-Pac if there is no one working on it, yes. But though I'm looking on code yet, so it will take bit time.

**Comment by djKooks** [comment]
@Dee-Pac as I commented, I'm trying to update test for APIs in kafka connector. But I'm still studying on module, so hope you could help.

I just added test for `NewOffsetRangesProvider`, but not quite sure for the purpose. Could you simply describe the use/purpose of this module?

**Comment by Dee-Pac** [comment]
@djKooks 

Please have a look at the method `toNewOffsetRanges`. It takes two sets of OffsetRange, does a diff between the right & left OffsetRange - provider a New OffsetRange for the consumer.
https://github.com/paypal/gimel/search?q=toNewOffsetRanges&unscoped_q=toNewOffsetRanges

Let's say a new KafkaConsumer is initiated, this consumer picks up the Left(OffsetRange) from Last Saved Checkpoint, Picks the Right(OffsetRange) from Latest Offsets in Kafka or what is passed. Using the two OffsetRange - the new OffsetRange for Current Consumption is calculated.

Please let me know if you need more clarification.

**Comment by djKooks** [comment]
@Dee-Pac thanks for help! I'll keep make updates.
