### ISSUE TITLE
[Test] scalatest maven plugin is missing from the modules

### ISSUE THREAD

**Issue by meisam** [paypal/gimel#63]
The test cases in modules are not running because the scalatest maven plugin is missing module pom files does not.

To reproduce:
```
$ mvn test
```
Expected behavior:
`DataSetUtilsSpec.scala` test suit should run and all test cases in it should pass.

Actual behavior:
`DataSetUtilsSpec.scala` does NOT run.

**Comment by Dee-Pac** [comment]
@meisam Could you please assign [Tag] to the issues. This one should probably be tagged `[Test]`
