### ISSUE TITLE
[Code Quality] Remove Unused Code

### ISSUE THREAD

**Issue by Dee-Pac** [paypal/gimel#66]
Remove unused code to improved code quality.

Refer here for complete report.

https://app.codacy.com/app/Dee-Pac/gimel/dashboard?bid=6990553

**Comment by akarsh3007** [comment]
Can I pick up this task?

**Comment by meisam** [comment]
Use the master branch, please. We use apache's branching workflow for git: https://deltaspike.apache.org/suggested-git-workflows.html

**Comment by Dee-Pac** [comment]
Closing stale issues.
