### ISSUE TITLE
[Connector] [Twitter] Create Gimel Twitter Connector

### ISSUE THREAD

**Issue by prabhu1984** [paypal/gimel#69]
Please add a Twitter connector on Gimel to support strea twitter tweets using twitter API to process as a dataframe.

https://github.com/vspiewak/twitter-sentiment-analysis/blob/master/src/main/scala/com/github/vspiewak/TwitterSentimentAnalysis.scala

**Comment by Dee-Pac** [comment]
We shall reopen the issue if a request arises.
