### ISSUE TITLE
[Upgrade] Update spark version to support Spark 2.3 version

### ISSUE THREAD

**Issue by bthilakraj** [paypal/gimel#96]
Upgrade Gimel to support Spark 2.3 version

**Comment by Dee-Pac** [comment]
@bthilakraj 

Just before we commit this PR into master - could you please create a `branch-2.2` out of master?

**Comment by bthilakraj** [comment]
@Dee-Pac : Sure Deepak

**Comment by Dee-Pac** [comment]
Closing this as this is taken care already.
